version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "poetry run python manage.py makemigrations core &&
         poetry run python manage.py migrate &&
          poetry run python manage.py shell -c 'from django.contrib.auth import get_user_model; User=get_user_model(); import os; \
             username=os.environ[\"DJANGO_SUPERUSER_USERNAME\"]; \
             email=os.environ[\"DJANGO_SUPERUSER_EMAIL\"]; \
             password=os.environ[\"DJANGO_SUPERUSER_PASSWORD\"]; \
             User.objects.filter(username=username).exists() or \
             User.objects.create_superuser(username, email, password)' &&
         poetry run python manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
    - ./frontend/semita-finder-frontend:/app
    - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: